=== minje46/Web_Programming/XML&DTD/Ex_2(Week#2)/tvschedule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="tvschedule" type="tvstype"/>
    <xs:complexType name="tvstype">
        <xs:sequence>
            <xs:element name="channel" type="chntype" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="chntype">
        <xs:sequence>
            <xs:element name="banner" type="xs:string"/>
            <xs:element name="day" type="daytype" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="chn" type="xs:string" use="required" />
    </xs:complexType>  
    <xs:complexType name="daytype">
        <xs:sequence>
            <xs:element name="date" type="xs:string" />
            <xs:choice maxOccurs="unbounded">
                <xs:element name="holiday" type="xs:string"/>
                <xs:element name="programslot" type="prgtype" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>  
    <xs:complexType name="prgtype">
        <xs:sequence>
            <xs:element name="time" type="xs:string"/>
            <xs:element name="title" type="ttltype"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="vtr" type="xs:string"/>
    </xs:complexType>   
    <xs:complexType name="ttltype">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="rating" type="xs:string" />
                <xs:attribute name="language" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== minje46/Web_Programming/XML&DTD/Ex_2(Week#2)/tvschedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<tvschedule name="Schedule"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="tvschedule.xsd">
<channel chn="mbc">
    <banner>MBC</banner>
    <day>
        <date>09/13/2018</date>
        <holiday>Thursday</holiday>
    </day>
    <day>
        <date>09/11/2018</date>
        <programslot>
            <time>8PM</time>
            <title>Soccer</title>
            <description>Korea vs. Chile</description>
        </programslot>
    </day>
</channel>
</tvschedule>
