=== minje46/Web_Programming/XML&DTD/Ex_1(Week#1)/bulletin.dtd
<!ELEMENT BOARD (NAME,ARTICLE+)>
<!ELEMENT ARTICLE (TITLE, W_MSG, W_ID, W_NAME, REPLY*)>
<!ELEMENT REPLY (R_MSG, W_ID, W_NAME)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT W_MSG (#PCDATA)>
<!ELEMENT W_ID (#PCDATA)>
<!ELEMENT W_NAME (#PCDATA)>
<!ELEMENT R_MSG (#PCDATA)>


<!ATTLIST ARTICLE AUTHOR CDATA #IMPLIED>
<!ATTLIST ARTICLE EDITOR CDATA #IMPLIED>
<!ATTLIST ARTICLE DATE CDATA #IMPLIED>
<!ATTLIST ARTICLE EDITION CDATA #IMPLIED>


<!ENTITY BOARD "KWAK_BULLETIN">

=== minje46/Web_Programming/XML&DTD/Ex_1(Week#1)/bulletin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BOARD SYSTEM "bulletin.dtd">

<BOARD>
    <NAME>STUDY WEB</NAME>
    <ARTICLE>
        <TITLE>EXERCISE_1</TITLE>
        <W_MSG>It is "so difficult" to do this easy task for me</W_MSG>
        <W_ID>201333450</W_ID>
        <W_NAME>kwak</W_NAME>
        <REPLY>
            <R_MSG>Cheer up!</R_MSG>
            <W_ID>201333470</W_ID>
            <W_NAME>An</W_NAME>
        </REPLY>
    </ARTICLE>
</BOARD>
